### ISSUE TITLE
Fatal error: Call to a member function get_template_part() only on plugin's activation

### ISSUE THREAD

**Issue by alessandrotesoro** [GaryJones/Gamajo-Template-Loader#36]
Hi there,

First of all thanks a lot for this awesome class. I'm using it with composer and it's super easy to intergrate. I'm using your class within a plugin of mine https://wordpress.org/plugins/wp-user-manager/, while 99.99% of users have no issues with it, I've had 2 cases now where the user is unable to activate the plugin because of the following error 

`Fatal error: Call to a member function get_template_part() on null in /wp-content/plugins/wp-user-manager/includes/wpum-shortcodes/shortcodes.php on line 38`

This is the file the error is referring to https://github.com/WPUserManager/wp-user-manager/blob/master/includes/wpum-shortcodes/shortcodes.php#L38 I can't seem to understand what's the issue, have I done something wrong? 

What I've noticed trying to understand the issue, is that this happens only on plugin's activation. 

The only time I've been able to replicate the issue on my end was when I had installed a premium version of the Yoast SEO plugin, it's was parsing shortcodes and doing some weird stuff, an update for the plugin was released and the issue disappeared ¯\_(ツ)_/¯.

The first user that had issue, I logged in via ftp, commented the shortcode, enabled the plugin, re-enabled the shortcode and everything just works fine, again ¯\_(ツ)_/¯. Now I've had a second report of a user with the same issue but I have no idea what's going on.

Have you encountered this issue before? 

Thank you!

**Comment by GaryJones** [comment]
Hi @alessandrotesoro.

I don't recall seeing anything like this before.

I've taken a look at your code, but can't spot anything obviously incorrect. The initial loading of the WPUM class is a little complex, but seems to make sense.

I'd probably try adding some debug statements (or use Xdebug) around when `WPUM_Template_Loader()` is being assigned to `$this->templates`, and then activate the plugin, and check if the property is being populated correctly. Alternatively, add a temporary constructor to `WPUM_Template_Loader()`.

At the point of plugin activation, or general usage, the Gamajo_Template_Loader doesn't do anything special - there's not even a constructor. Since the error says that `WPUM()->templates` is `null`, then it suggests the error is somewhere in your code, rather than mine.

Other than the `register_plugin_activation()` line, which needs to happen early, I think much of the rest of the `WPUM()` could happen at or after `plugins_loaded`, rather than just the `init` stuff.

Right now, during parsing of the plugin file, it:
 - loads the main plugin file
 - defines and calls `WPUM()`
 - which instantiates WPUM object via Singleton approach
 - which calls the constructor
 - which autoloads everything from Composer, including Gamajo_Template_Loader
 - then calls the include() method, which loads a whole bunch of files
 - including the `shortcodes.php`
 - which calls `add_shortcode()` a bunch of times
 - *and only later* is the `init_hooks()` method called
 - which adds an `init` callback to `plugins_loaded`
 - which only then populates `WPUM->templates` with a new instance of `WPUM_Template_loader`, which is what the message-related shortcode expected to be present.

If there was another plugin that was triggering the shortcode callback before `plugins_loaded` had run, then you'd get the scenario the message relates to.

Maybe consider defering `add_shortcode()` calls until after `plugins_loaded`, instead of calling them during what is essentially parsing of the plugin file.

**Comment by alessandrotesoro** [comment]
Hi @GaryJones 

Thanks a lot for the detailed answer, I'll take your suggestion on board and see what happens. I've now just had another user report the same issue, and like first report I had, the issue seems to be a conflict with Yoast SEO, the user managed to activate my plugin after disabling yoast and renabling it after WPUM was active.
